import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Loader2, Sparkles, Activity, Calendar, Lightbulb } from "lucide-react";

export default function Recommendations() {
    const [loading, setLoading] = useState(true);

    // Mock Data for Demo
    const summary = {
        date: new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' }),
        average_score: -0.4,
        mood_label: "Anxious",
        summary_text: "Today has been a bit challenging. You expressed concern about upcoming deadlines and felt a sense of overwhelm in the afternoon, though you stabilized towards the evening.",
        recommendation: "Since you mentioned feeling 'stuck', try the 5-minute 'Box Breathing' technique we practiced. Also, remember your win from yesterday - you are capable of handling this.",
        needs_intervention: false
    };

    useEffect(() => {
        setTimeout(() => setLoading(false), 1500); // Simulate AI generation delay
    }, []);

    if (loading) {
        return (
            <div className="flex flex-col items-center justify-center h-96 gap-4">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
                <p className="text-muted-foreground animate-pulse">Analyzing your daily patterns...</p>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <div>
                <h2 className="text-3xl font-bold tracking-tight text-foreground">MindSphere Recommendations</h2>
                <p className="text-muted-foreground mt-2">AI-driven insights based on your daily interactions.</p>
            </div>

            <div className="grid gap-6 md:grid-cols-2">
                {/* Main Summary Card */}
                <Card className="col-span-2 border-primary/20 bg-primary/5">
                    <CardHeader>
                        <div className="flex items-center gap-2">
                            <Sparkles className="h-5 w-5 text-primary" />
                            <CardTitle>Daily Digest • {summary.date}</CardTitle>
                        </div>
                        <CardDescription>Generated by analyzing your conversation logs today.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <div className="p-4 bg-background/50 rounded-lg border border-border">
                            <p className="text-lg leading-relaxed">{summary.summary_text}</p>
                        </div>

                        <div className="flex items-start gap-3 p-4 bg-background/80 rounded-lg border-l-4 border-primary">
                            <Lightbulb className="h-5 w-5 text-primary mt-1" />
                            <div>
                                <h4 className="font-semibold text-foreground">Suggestion for Tonight</h4>
                                <p className="text-muted-foreground">{summary.recommendation}</p>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                {/* Metrics Card */}
                <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <Activity className="h-5 w-5 text-muted-foreground" />
                            Clinical Status
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div className="flex items-center justify-between mb-2">
                            <span className="text-sm font-medium">Average LEAS Score</span>
                            <span className={`text-xl font-bold ${summary.average_score < 0 ? 'text-orange-500' : 'text-green-500'}`}>
                                {summary.average_score}
                            </span>
                        </div>
                        <div className="h-2 bg-secondary rounded-full overflow-hidden">
                            <div
                                className={`h-full ${summary.average_score < 0 ? 'bg-orange-500' : 'bg-green-500'}`}
                                style={{ width: `${(summary.average_score + 1) * 50}%` }}
                            />
                        </div>
                        <p className="text-xs text-muted-foreground mt-2">
                            Status: <span className="font-medium text-foreground">{summary.mood_label}</span>
                        </p>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
